using System;
using System.Runtime.InteropServices;

namespace Proton
{
	static class GL30
	{
		#region Constants
		public const uint GL_COMPARE_REF_TO_TEXTURE = 34894;
		public const uint GL_CLIP_DISTANCE0 = 12288;
		public const uint GL_CLIP_DISTANCE1 = 12289;
		public const uint GL_CLIP_DISTANCE2 = 12290;
		public const uint GL_CLIP_DISTANCE3 = 12291;
		public const uint GL_CLIP_DISTANCE4 = 12292;
		public const uint GL_CLIP_DISTANCE5 = 12293;
		public const uint GL_CLIP_DISTANCE6 = 12294;
		public const uint GL_CLIP_DISTANCE7 = 12295;
		public const uint GL_MAX_CLIP_DISTANCES = 3378;
		public const uint GL_MAJOR_VERSION = 33307;
		public const uint GL_MINOR_VERSION = 33308;
		public const uint GL_NUM_EXTENSIONS = 33309;
		public const uint GL_CONTEXT_FLAGS = 33310;
		public const uint GL_COMPRESSED_RED = 33317;
		public const uint GL_COMPRESSED_RG = 33318;
		public const uint GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 1;
		public const uint GL_RGBA32F = 34836;
		public const uint GL_RGB32F = 34837;
		public const uint GL_RGBA16F = 34842;
		public const uint GL_RGB16F = 34843;
		public const uint GL_VERTEX_ATTRIB_ARRAY_INTEGER = 35069;
		public const uint GL_MAX_ARRAY_TEXTURE_LAYERS = 35071;
		public const uint GL_MIN_PROGRAM_TEXEL_OFFSET = 35076;
		public const uint GL_MAX_PROGRAM_TEXEL_OFFSET = 35077;
		public const uint GL_CLAMP_READ_COLOR = 35100;
		public const uint GL_FIXED_ONLY = 35101;
		public const uint GL_MAX_VARYING_COMPONENTS = 35659;
		public const uint GL_TEXTURE_1D_ARRAY = 35864;
		public const uint GL_PROXY_TEXTURE_1D_ARRAY = 35865;
		public const uint GL_TEXTURE_2D_ARRAY = 35866;
		public const uint GL_PROXY_TEXTURE_2D_ARRAY = 35867;
		public const uint GL_TEXTURE_BINDING_1D_ARRAY = 35868;
		public const uint GL_TEXTURE_BINDING_2D_ARRAY = 35869;
		public const uint GL_R11F_G11F_B10F = 35898;
		public const uint GL_UNSIGNED_INT_10F_11F_11F_REV = 35899;
		public const uint GL_RGB9_E5 = 35901;
		public const uint GL_UNSIGNED_INT_5_9_9_9_REV = 35902;
		public const uint GL_TEXTURE_SHARED_SIZE = 35903;
		public const uint GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 35958;
		public const uint GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 35967;
		public const uint GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 35968;
		public const uint GL_TRANSFORM_FEEDBACK_VARYINGS = 35971;
		public const uint GL_TRANSFORM_FEEDBACK_BUFFER_START = 35972;
		public const uint GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 35973;
		public const uint GL_PRIMITIVES_GENERATED = 35975;
		public const uint GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 35976;
		public const uint GL_RASTERIZER_DISCARD = 35977;
		public const uint GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 35978;
		public const uint GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 35979;
		public const uint GL_INTERLEAVED_ATTRIBS = 35980;
		public const uint GL_SEPARATE_ATTRIBS = 35981;
		public const uint GL_TRANSFORM_FEEDBACK_BUFFER = 35982;
		public const uint GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 35983;
		public const uint GL_RGBA32UI = 36208;
		public const uint GL_RGB32UI = 36209;
		public const uint GL_RGBA16UI = 36214;
		public const uint GL_RGB16UI = 36215;
		public const uint GL_RGBA8UI = 36220;
		public const uint GL_RGB8UI = 36221;
		public const uint GL_RGBA32I = 36226;
		public const uint GL_RGB32I = 36227;
		public const uint GL_RGBA16I = 36232;
		public const uint GL_RGB16I = 36233;
		public const uint GL_RGBA8I = 36238;
		public const uint GL_RGB8I = 36239;
		public const uint GL_RED_INTEGER = 36244;
		public const uint GL_GREEN_INTEGER = 36245;
		public const uint GL_BLUE_INTEGER = 36246;
		public const uint GL_RGB_INTEGER = 36248;
		public const uint GL_RGBA_INTEGER = 36249;
		public const uint GL_BGR_INTEGER = 36250;
		public const uint GL_BGRA_INTEGER = 36251;
		public const uint GL_SAMPLER_1D_ARRAY = 36288;
		public const uint GL_SAMPLER_2D_ARRAY = 36289;
		public const uint GL_SAMPLER_1D_ARRAY_SHADOW = 36291;
		public const uint GL_SAMPLER_2D_ARRAY_SHADOW = 36292;
		public const uint GL_SAMPLER_CUBE_SHADOW = 36293;
		public const uint GL_UNSIGNED_INT_VEC2 = 36294;
		public const uint GL_UNSIGNED_INT_VEC3 = 36295;
		public const uint GL_UNSIGNED_INT_VEC4 = 36296;
		public const uint GL_INT_SAMPLER_1D = 36297;
		public const uint GL_INT_SAMPLER_2D = 36298;
		public const uint GL_INT_SAMPLER_3D = 36299;
		public const uint GL_INT_SAMPLER_CUBE = 36300;
		public const uint GL_INT_SAMPLER_1D_ARRAY = 36302;
		public const uint GL_INT_SAMPLER_2D_ARRAY = 36303;
		public const uint GL_UNSIGNED_INT_SAMPLER_1D = 36305;
		public const uint GL_UNSIGNED_INT_SAMPLER_2D = 36306;
		public const uint GL_UNSIGNED_INT_SAMPLER_3D = 36307;
		public const uint GL_UNSIGNED_INT_SAMPLER_CUBE = 36308;
		public const uint GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 36310;
		public const uint GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 36311;
		public const uint GL_QUERY_WAIT = 36371;
		public const uint GL_QUERY_NO_WAIT = 36372;
		public const uint GL_QUERY_BY_REGION_WAIT = 36373;
		public const uint GL_QUERY_BY_REGION_NO_WAIT = 36374;
		public const uint GL_BUFFER_ACCESS_FLAGS = 37151;
		public const uint GL_BUFFER_MAP_LENGTH = 37152;
		public const uint GL_BUFFER_MAP_OFFSET = 37153;
		public const uint GL_DEPTH_COMPONENT32F = 36012;
		public const uint GL_DEPTH32F_STENCIL8 = 36013;
		public const uint GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 36269;
		public const uint GL_INVALID_FRAMEBUFFER_OPERATION = 1286;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 33296;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 33297;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 33298;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 33299;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 33300;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 33301;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 33302;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 33303;
		public const uint GL_FRAMEBUFFER_DEFAULT = 33304;
		public const uint GL_FRAMEBUFFER_UNDEFINED = 33305;
		public const uint GL_DEPTH_STENCIL_ATTACHMENT = 33306;
		public const uint GL_MAX_RENDERBUFFER_SIZE = 34024;
		public const uint GL_DEPTH_STENCIL = 34041;
		public const uint GL_UNSIGNED_INT_24_8 = 34042;
		public const uint GL_DEPTH24_STENCIL8 = 35056;
		public const uint GL_TEXTURE_STENCIL_SIZE = 35057;
		public const uint GL_TEXTURE_RED_TYPE = 35856;
		public const uint GL_TEXTURE_GREEN_TYPE = 35857;
		public const uint GL_TEXTURE_BLUE_TYPE = 35858;
		public const uint GL_TEXTURE_ALPHA_TYPE = 35859;
		public const uint GL_TEXTURE_DEPTH_TYPE = 35862;
		public const uint GL_UNSIGNED_NORMALIZED = 35863;
		public const uint GL_FRAMEBUFFER_BINDING = 36006;
		public const uint GL_DRAW_FRAMEBUFFER_BINDING = 36006;
		public const uint GL_RENDERBUFFER_BINDING = 36007;
		public const uint GL_READ_FRAMEBUFFER = 36008;
		public const uint GL_DRAW_FRAMEBUFFER = 36009;
		public const uint GL_READ_FRAMEBUFFER_BINDING = 36010;
		public const uint GL_RENDERBUFFER_SAMPLES = 36011;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 36048;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 36049;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 36050;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 36051;
		public const uint GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 36052;
		public const uint GL_FRAMEBUFFER_COMPLETE = 36053;
		public const uint GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 36054;
		public const uint GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 36055;
		public const uint GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 36059;
		public const uint GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 36060;
		public const uint GL_FRAMEBUFFER_UNSUPPORTED = 36061;
		public const uint GL_MAX_COLOR_ATTACHMENTS = 36063;
		public const uint GL_COLOR_ATTACHMENT0 = 36064;
		public const uint GL_COLOR_ATTACHMENT1 = 36065;
		public const uint GL_COLOR_ATTACHMENT2 = 36066;
		public const uint GL_COLOR_ATTACHMENT3 = 36067;
		public const uint GL_COLOR_ATTACHMENT4 = 36068;
		public const uint GL_COLOR_ATTACHMENT5 = 36069;
		public const uint GL_COLOR_ATTACHMENT6 = 36070;
		public const uint GL_COLOR_ATTACHMENT7 = 36071;
		public const uint GL_COLOR_ATTACHMENT8 = 36072;
		public const uint GL_COLOR_ATTACHMENT9 = 36073;
		public const uint GL_COLOR_ATTACHMENT10 = 36074;
		public const uint GL_COLOR_ATTACHMENT11 = 36075;
		public const uint GL_COLOR_ATTACHMENT12 = 36076;
		public const uint GL_COLOR_ATTACHMENT13 = 36077;
		public const uint GL_COLOR_ATTACHMENT14 = 36078;
		public const uint GL_COLOR_ATTACHMENT15 = 36079;
		public const uint GL_COLOR_ATTACHMENT16 = 36080;
		public const uint GL_COLOR_ATTACHMENT17 = 36081;
		public const uint GL_COLOR_ATTACHMENT18 = 36082;
		public const uint GL_COLOR_ATTACHMENT19 = 36083;
		public const uint GL_COLOR_ATTACHMENT20 = 36084;
		public const uint GL_COLOR_ATTACHMENT21 = 36085;
		public const uint GL_COLOR_ATTACHMENT22 = 36086;
		public const uint GL_COLOR_ATTACHMENT23 = 36087;
		public const uint GL_COLOR_ATTACHMENT24 = 36088;
		public const uint GL_COLOR_ATTACHMENT25 = 36089;
		public const uint GL_COLOR_ATTACHMENT26 = 36090;
		public const uint GL_COLOR_ATTACHMENT27 = 36091;
		public const uint GL_COLOR_ATTACHMENT28 = 36092;
		public const uint GL_COLOR_ATTACHMENT29 = 36093;
		public const uint GL_COLOR_ATTACHMENT30 = 36094;
		public const uint GL_COLOR_ATTACHMENT31 = 36095;
		public const uint GL_DEPTH_ATTACHMENT = 36096;
		public const uint GL_STENCIL_ATTACHMENT = 36128;
		public const uint GL_FRAMEBUFFER = 36160;
		public const uint GL_RENDERBUFFER = 36161;
		public const uint GL_RENDERBUFFER_WIDTH = 36162;
		public const uint GL_RENDERBUFFER_HEIGHT = 36163;
		public const uint GL_RENDERBUFFER_INTERNAL_FORMAT = 36164;
		public const uint GL_STENCIL_INDEX1 = 36166;
		public const uint GL_STENCIL_INDEX4 = 36167;
		public const uint GL_STENCIL_INDEX8 = 36168;
		public const uint GL_STENCIL_INDEX16 = 36169;
		public const uint GL_RENDERBUFFER_RED_SIZE = 36176;
		public const uint GL_RENDERBUFFER_GREEN_SIZE = 36177;
		public const uint GL_RENDERBUFFER_BLUE_SIZE = 36178;
		public const uint GL_RENDERBUFFER_ALPHA_SIZE = 36179;
		public const uint GL_RENDERBUFFER_DEPTH_SIZE = 36180;
		public const uint GL_RENDERBUFFER_STENCIL_SIZE = 36181;
		public const uint GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 36182;
		public const uint GL_MAX_SAMPLES = 36183;
		public const uint GL_FRAMEBUFFER_SRGB = 36281;
		public const uint GL_HALF_FLOAT = 5131;
		public const uint GL_MAP_READ_BIT = 1;
		public const uint GL_MAP_WRITE_BIT = 2;
		public const uint GL_MAP_INVALIDATE_RANGE_BIT = 4;
		public const uint GL_MAP_INVALIDATE_BUFFER_BIT = 8;
		public const uint GL_MAP_FLUSH_EXPLICIT_BIT = 16;
		public const uint GL_MAP_UNSYNCHRONIZED_BIT = 32;
		public const uint GL_COMPRESSED_RED_RGTC1 = 36283;
		public const uint GL_COMPRESSED_SIGNED_RED_RGTC1 = 36284;
		public const uint GL_COMPRESSED_RG_RGTC2 = 36285;
		public const uint GL_COMPRESSED_SIGNED_RG_RGTC2 = 36286;
		public const uint GL_RG = 33319;
		public const uint GL_RG_INTEGER = 33320;
		public const uint GL_R8 = 33321;
		public const uint GL_R16 = 33322;
		public const uint GL_RG8 = 33323;
		public const uint GL_RG16 = 33324;
		public const uint GL_R16F = 33325;
		public const uint GL_R32F = 33326;
		public const uint GL_RG16F = 33327;
		public const uint GL_RG32F = 33328;
		public const uint GL_R8I = 33329;
		public const uint GL_R8UI = 33330;
		public const uint GL_R16I = 33331;
		public const uint GL_R16UI = 33332;
		public const uint GL_R32I = 33333;
		public const uint GL_R32UI = 33334;
		public const uint GL_RG8I = 33335;
		public const uint GL_RG8UI = 33336;
		public const uint GL_RG16I = 33337;
		public const uint GL_RG16UI = 33338;
		public const uint GL_RG32I = 33339;
		public const uint GL_RG32UI = 33340;
		public const uint GL_VERTEX_ARRAY_BINDING = 34229;
		#endregion

		#region Delegates
		public delegate void PFNGLCOLORMASKIPROC(uint index, byte r, byte g, byte b, byte a);
		public delegate void PFNGLGETBOOLEANI_VPROC(uint target, uint index, IntPtr data);
		public delegate void PFNGLGETINTEGERI_VPROC(uint target, uint index, ref int data);
		public delegate void PFNGLENABLEIPROC(uint target, uint index);
		public delegate void PFNGLDISABLEIPROC(uint target, uint index);
		public delegate byte PFNGLISENABLEDIPROC(uint target, uint index);
		public delegate void PFNGLBEGINTRANSFORMFEEDBACKPROC(uint primitiveMode);
		public delegate void PFNGLENDTRANSFORMFEEDBACKPROC();
		public delegate void PFNGLBINDBUFFERRANGEPROC(uint target, uint index, uint buffer, int offset, int size);
		public delegate void PFNGLBINDBUFFERBASEPROC(uint target, uint index, uint buffer);
		public delegate void PFNGLTRANSFORMFEEDBACKVARYINGSPROC(uint program, int count, IntPtr varyings, uint bufferMode);
		public delegate void PFNGLGETTRANSFORMFEEDBACKVARYINGPROC(uint program, uint index, int bufSize, ref int length, ref int size, ref uint type, IntPtr name);
		public delegate void PFNGLCLAMPCOLORPROC(uint target, uint clamp);
		public delegate void PFNGLBEGINCONDITIONALRENDERPROC(uint id, uint mode);
		public delegate void PFNGLENDCONDITIONALRENDERPROC();
		public delegate void PFNGLVERTEXATTRIBIPOINTERPROC(uint index, int size, uint type, int stride, IntPtr pointer);
		public delegate void PFNGLGETVERTEXATTRIBIIVPROC(uint index, uint pname, ref int parameters);
		public delegate void PFNGLGETVERTEXATTRIBIUIVPROC(uint index, uint pname, ref uint parameters);
		public delegate void PFNGLVERTEXATTRIBI1IPROC(uint index, int x);
		public delegate void PFNGLVERTEXATTRIBI2IPROC(uint index, int x, int y);
		public delegate void PFNGLVERTEXATTRIBI3IPROC(uint index, int x, int y, int z);
		public delegate void PFNGLVERTEXATTRIBI4IPROC(uint index, int x, int y, int z, int w);
		public delegate void PFNGLVERTEXATTRIBI1UIPROC(uint index, uint x);
		public delegate void PFNGLVERTEXATTRIBI2UIPROC(uint index, uint x, uint y);
		public delegate void PFNGLVERTEXATTRIBI3UIPROC(uint index, uint x, uint y, uint z);
		public delegate void PFNGLVERTEXATTRIBI4UIPROC(uint index, uint x, uint y, uint z, uint w);
		public delegate void PFNGLVERTEXATTRIBI1IVPROC(uint index, ref int v);
		public delegate void PFNGLVERTEXATTRIBI2IVPROC(uint index, ref int v);
		public delegate void PFNGLVERTEXATTRIBI3IVPROC(uint index, ref int v);
		public delegate void PFNGLVERTEXATTRIBI4IVPROC(uint index, ref int v);
		public delegate void PFNGLVERTEXATTRIBI1UIVPROC(uint index, ref uint v);
		public delegate void PFNGLVERTEXATTRIBI2UIVPROC(uint index, ref uint v);
		public delegate void PFNGLVERTEXATTRIBI3UIVPROC(uint index, ref uint v);
		public delegate void PFNGLVERTEXATTRIBI4UIVPROC(uint index, ref uint v);
		public delegate void PFNGLVERTEXATTRIBI4BVPROC(uint index, [In] [MarshalAs(UnmanagedType.LPStr)] string v);
		public delegate void PFNGLVERTEXATTRIBI4SVPROC(uint index, ref short v);
		public delegate void PFNGLVERTEXATTRIBI4UBVPROC(uint index, [In] [MarshalAs(UnmanagedType.LPStr)] string v);
		public delegate void PFNGLVERTEXATTRIBI4USVPROC(uint index, ref ushort v);
		public delegate void PFNGLGETUNIFORMUIVPROC(uint program, int location, ref uint parameters);
		public delegate void PFNGLBINDFRAGDATALOCATIONPROC(uint program, uint color, [In] [MarshalAs(UnmanagedType.LPStr)] string name);
		public delegate int PFNGLGETFRAGDATALOCATIONPROC(uint program, [In] [MarshalAs(UnmanagedType.LPStr)] string name);
		public delegate void PFNGLUNIFORM1UIPROC(int location, uint v0);
		public delegate void PFNGLUNIFORM2UIPROC(int location, uint v0, uint v1);
		public delegate void PFNGLUNIFORM3UIPROC(int location, uint v0, uint v1, uint v2);
		public delegate void PFNGLUNIFORM4UIPROC(int location, uint v0, uint v1, uint v2, uint v3);
		public delegate void PFNGLUNIFORM1UIVPROC(int location, int count, ref uint value);
		public delegate void PFNGLUNIFORM2UIVPROC(int location, int count, ref uint value);
		public delegate void PFNGLUNIFORM3UIVPROC(int location, int count, ref uint value);
		public delegate void PFNGLUNIFORM4UIVPROC(int location, int count, ref uint value);
		public delegate void PFNGLTEXPARAMETERIIVPROC(uint target, uint pname, ref int parameters);
		public delegate void PFNGLTEXPARAMETERIUIVPROC(uint target, uint pname, ref uint parameters);
		public delegate void PFNGLGETTEXPARAMETERIIVPROC(uint target, uint pname, ref int parameters);
		public delegate void PFNGLGETTEXPARAMETERIUIVPROC(uint target, uint pname, ref uint parameters);
		public delegate void PFNGLCLEARBUFFERIVPROC(uint buffer, int drawbuffer, ref int value);
		public delegate void PFNGLCLEARBUFFERUIVPROC(uint buffer, int drawbuffer, ref uint value);
		public delegate void PFNGLCLEARBUFFERFVPROC(uint buffer, int drawbuffer, ref float value);
		public delegate void PFNGLCLEARBUFFERFIPROC(uint buffer, int drawbuffer, float depth, int stencil);
		public delegate IntPtr PFNGLGETSTRINGIPROC(uint name, uint index);
		public delegate byte PFNGLISRENDERBUFFERPROC(uint renderbuffer);
		public delegate void PFNGLBINDRENDERBUFFERPROC(uint target, uint renderbuffer);
		public delegate void PFNGLDELETERENDERBUFFERSPROC(int n, ref uint renderbuffers);
		public delegate void PFNGLGENRENDERBUFFERSPROC(int n, ref uint renderbuffers);
		public delegate void PFNGLRENDERBUFFERSTORAGEPROC(uint target, uint internalformat, int width, int height);
		public delegate void PFNGLGETRENDERBUFFERPARAMETERIVPROC(uint target, uint pname, ref int parameters);
		public delegate byte PFNGLISFRAMEBUFFERPROC(uint framebuffer);
		public delegate void PFNGLBINDFRAMEBUFFERPROC(uint target, uint framebuffer);
		public delegate void PFNGLDELETEFRAMEBUFFERSPROC(int n, ref uint framebuffers);
		public delegate void PFNGLGENFRAMEBUFFERSPROC(int n, ref uint framebuffers);
		public delegate uint PFNGLCHECKFRAMEBUFFERSTATUSPROC(uint target);
		public delegate void PFNGLFRAMEBUFFERTEXTURE1DPROC(uint target, uint attachment, uint textarget, uint texture, int level);
		public delegate void PFNGLFRAMEBUFFERTEXTURE2DPROC(uint target, uint attachment, uint textarget, uint texture, int level);
		public delegate void PFNGLFRAMEBUFFERTEXTURE3DPROC(uint target, uint attachment, uint textarget, uint texture, int level, int zoffset);
		public delegate void PFNGLFRAMEBUFFERRENDERBUFFERPROC(uint target, uint attachment, uint renderbuffertarget, uint renderbuffer);
		public delegate void PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC(uint target, uint attachment, uint pname, ref int parameters);
		public delegate void PFNGLGENERATEMIPMAPPROC(uint target);
		public delegate void PFNGLBLITFRAMEBUFFERPROC(int srcX0, int srcY0, int srcX1, int srcY1, int dstX0, int dstY0, int dstX1, int dstY1, uint mask, uint filter);
		public delegate void PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC(uint target, int samples, uint internalformat, int width, int height);
		public delegate void PFNGLFRAMEBUFFERTEXTURELAYERPROC(uint target, uint attachment, uint texture, int level, int layer);
		public delegate IntPtr PFNGLMAPBUFFERRANGEPROC(uint target, int offset, int length, uint access);
		public delegate void PFNGLFLUSHMAPPEDBUFFERRANGEPROC(uint target, int offset, int length);
		public delegate void PFNGLBINDVERTEXARRAYPROC(uint array);
		public delegate void PFNGLDELETEVERTEXARRAYSPROC(int n, ref uint arrays);
		public delegate void PFNGLGENVERTEXARRAYSPROC(int n, ref uint arrays);
		public delegate byte PFNGLISVERTEXARRAYPROC(uint array);
		#endregion

		#region Methods
		public static PFNGLCOLORMASKIPROC glColorMaski;
		public static PFNGLGETBOOLEANI_VPROC glGetBooleani_v;
		public static PFNGLGETINTEGERI_VPROC glGetIntegeri_v;
		public static PFNGLENABLEIPROC glEnablei;
		public static PFNGLDISABLEIPROC glDisablei;
		public static PFNGLISENABLEDIPROC glIsEnabledi;
		public static PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback;
		public static PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback;
		public static PFNGLBINDBUFFERRANGEPROC glBindBufferRange;
		public static PFNGLBINDBUFFERBASEPROC glBindBufferBase;
		public static PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings;
		public static PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying;
		public static PFNGLCLAMPCOLORPROC glClampColor;
		public static PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender;
		public static PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender;
		public static PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer;
		public static PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv;
		public static PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv;
		public static PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i;
		public static PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i;
		public static PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i;
		public static PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i;
		public static PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui;
		public static PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui;
		public static PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui;
		public static PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui;
		public static PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv;
		public static PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv;
		public static PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv;
		public static PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv;
		public static PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv;
		public static PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv;
		public static PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv;
		public static PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv;
		public static PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv;
		public static PFNGLVERTEXATTRIBI4SVPROC glVertexAttribI4sv;
		public static PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv;
		public static PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv;
		public static PFNGLGETUNIFORMUIVPROC glGetUniformuiv;
		public static PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation;
		public static PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation;
		public static PFNGLUNIFORM1UIPROC glUniform1ui;
		public static PFNGLUNIFORM2UIPROC glUniform2ui;
		public static PFNGLUNIFORM3UIPROC glUniform3ui;
		public static PFNGLUNIFORM4UIPROC glUniform4ui;
		public static PFNGLUNIFORM1UIVPROC glUniform1uiv;
		public static PFNGLUNIFORM2UIVPROC glUniform2uiv;
		public static PFNGLUNIFORM3UIVPROC glUniform3uiv;
		public static PFNGLUNIFORM4UIVPROC glUniform4uiv;
		public static PFNGLTEXPARAMETERIIVPROC glTexParameterIiv;
		public static PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv;
		public static PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;
		public static PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;
		public static PFNGLCLEARBUFFERIVPROC glClearBufferiv;
		public static PFNGLCLEARBUFFERUIVPROC glClearBufferuiv;
		public static PFNGLCLEARBUFFERFVPROC glClearBufferfv;
		public static PFNGLCLEARBUFFERFIPROC glClearBufferfi;
		public static PFNGLGETSTRINGIPROC glGetStringi;
		public static PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
		public static PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
		public static PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
		public static PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
		public static PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
		public static PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
		public static PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
		public static PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
		public static PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
		public static PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
		public static PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
		public static PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D;
		public static PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
		public static PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D;
		public static PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
		public static PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
		public static PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
		public static PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
		public static PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
		public static PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
		public static PFNGLMAPBUFFERRANGEPROC glMapBufferRange;
		public static PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange;
		public static PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
		public static PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
		public static PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
		public static PFNGLISVERTEXARRAYPROC glIsVertexArray;
		#endregion
	}
}
