using System;
using System.Runtime.InteropServices;

namespace Proton
{
    static class GL43
    {
        #region Constants
        public const uint GL_NUM_SHADING_LANGUAGE_VERSIONS = 33513;
        public const uint GL_VERTEX_ATTRIB_ARRAY_LONG = 34638;
        public const uint GL_COMPRESSED_RGB8_ETC2 = 37492;
        public const uint GL_COMPRESSED_SRGB8_ETC2 = 37493;
        public const uint GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 37494;
        public const uint GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 37495;
        public const uint GL_COMPRESSED_RGBA8_ETC2_EAC = 37496;
        public const uint GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 37497;
        public const uint GL_COMPRESSED_R11_EAC = 37488;
        public const uint GL_COMPRESSED_SIGNED_R11_EAC = 37489;
        public const uint GL_COMPRESSED_RG11_EAC = 37490;
        public const uint GL_COMPRESSED_SIGNED_RG11_EAC = 37491;
        public const uint GL_PRIMITIVE_RESTART_FIXED_INDEX = 36201;
        public const uint GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 36202;
        public const uint GL_MAX_ELEMENT_INDEX = 36203;
        public const uint GL_COMPUTE_SHADER = 37305;
        public const uint GL_MAX_COMPUTE_UNIFORM_BLOCKS = 37307;
        public const uint GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 37308;
        public const uint GL_MAX_COMPUTE_IMAGE_UNIFORMS = 37309;
        public const uint GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 33378;
        public const uint GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 33379;
        public const uint GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 33380;
        public const uint GL_MAX_COMPUTE_ATOMIC_COUNTERS = 33381;
        public const uint GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 33382;
        public const uint GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 37099;
        public const uint GL_MAX_COMPUTE_WORK_GROUP_COUNT = 37310;
        public const uint GL_MAX_COMPUTE_WORK_GROUP_SIZE = 37311;
        public const uint GL_COMPUTE_WORK_GROUP_SIZE = 33383;
        public const uint GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = 37100;
        public const uint GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER = 37101;
        public const uint GL_DISPATCH_INDIRECT_BUFFER = 37102;
        public const uint GL_DISPATCH_INDIRECT_BUFFER_BINDING = 37103;
        public const uint GL_COMPUTE_SHADER_BIT = 32;
        public const uint GL_DEBUG_OUTPUT_SYNCHRONOUS = 33346;
        public const uint GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 33347;
        public const uint GL_DEBUG_CALLBACK_FUNCTION = 33348;
        public const uint GL_DEBUG_CALLBACK_USER_PARAM = 33349;
        public const uint GL_DEBUG_SOURCE_API = 33350;
        public const uint GL_DEBUG_SOURCE_WINDOW_SYSTEM = 33351;
        public const uint GL_DEBUG_SOURCE_SHADER_COMPILER = 33352;
        public const uint GL_DEBUG_SOURCE_THIRD_PARTY = 33353;
        public const uint GL_DEBUG_SOURCE_APPLICATION = 33354;
        public const uint GL_DEBUG_SOURCE_OTHER = 33355;
        public const uint GL_DEBUG_TYPE_ERROR = 33356;
        public const uint GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 33357;
        public const uint GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 33358;
        public const uint GL_DEBUG_TYPE_PORTABILITY = 33359;
        public const uint GL_DEBUG_TYPE_PERFORMANCE = 33360;
        public const uint GL_DEBUG_TYPE_OTHER = 33361;
        public const uint GL_MAX_DEBUG_MESSAGE_LENGTH = 37187;
        public const uint GL_MAX_DEBUG_LOGGED_MESSAGES = 37188;
        public const uint GL_DEBUG_LOGGED_MESSAGES = 37189;
        public const uint GL_DEBUG_SEVERITY_HIGH = 37190;
        public const uint GL_DEBUG_SEVERITY_MEDIUM = 37191;
        public const uint GL_DEBUG_SEVERITY_LOW = 37192;
        public const uint GL_DEBUG_TYPE_MARKER = 33384;
        public const uint GL_DEBUG_TYPE_PUSH_GROUP = 33385;
        public const uint GL_DEBUG_TYPE_POP_GROUP = 33386;
        public const uint GL_DEBUG_SEVERITY_NOTIFICATION = 33387;
        public const uint GL_MAX_DEBUG_GROUP_STACK_DEPTH = 33388;
        public const uint GL_DEBUG_GROUP_STACK_DEPTH = 33389;
        public const uint GL_BUFFER = 33504;
        public const uint GL_SHADER = 33505;
        public const uint GL_PROGRAM = 33506;
        public const uint GL_QUERY = 33507;
        public const uint GL_PROGRAM_PIPELINE = 33508;
        public const uint GL_SAMPLER = 33510;
        public const uint GL_MAX_LABEL_LENGTH = 33512;
        public const uint GL_DEBUG_OUTPUT = 37600;
        public const int GL_CONTEXT_FLAG_DEBUG_BIT = 2;
        public const uint GL_MAX_UNIFORM_LOCATIONS = 33390;
        public const uint GL_FRAMEBUFFER_DEFAULT_WIDTH = 37648;
        public const uint GL_FRAMEBUFFER_DEFAULT_HEIGHT = 37649;
        public const uint GL_FRAMEBUFFER_DEFAULT_LAYERS = 37650;
        public const uint GL_FRAMEBUFFER_DEFAULT_SAMPLES = 37651;
        public const uint GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 37652;
        public const uint GL_MAX_FRAMEBUFFER_WIDTH = 37653;
        public const uint GL_MAX_FRAMEBUFFER_HEIGHT = 37654;
        public const uint GL_MAX_FRAMEBUFFER_LAYERS = 37655;
        public const uint GL_MAX_FRAMEBUFFER_SAMPLES = 37656;
        public const uint GL_INTERNALFORMAT_SUPPORTED = 33391;
        public const uint GL_INTERNALFORMAT_PREFERRED = 33392;
        public const uint GL_INTERNALFORMAT_RED_SIZE = 33393;
        public const uint GL_INTERNALFORMAT_GREEN_SIZE = 33394;
        public const uint GL_INTERNALFORMAT_BLUE_SIZE = 33395;
        public const uint GL_INTERNALFORMAT_ALPHA_SIZE = 33396;
        public const uint GL_INTERNALFORMAT_DEPTH_SIZE = 33397;
        public const uint GL_INTERNALFORMAT_STENCIL_SIZE = 33398;
        public const uint GL_INTERNALFORMAT_SHARED_SIZE = 33399;
        public const uint GL_INTERNALFORMAT_RED_TYPE = 33400;
        public const uint GL_INTERNALFORMAT_GREEN_TYPE = 33401;
        public const uint GL_INTERNALFORMAT_BLUE_TYPE = 33402;
        public const uint GL_INTERNALFORMAT_ALPHA_TYPE = 33403;
        public const uint GL_INTERNALFORMAT_DEPTH_TYPE = 33404;
        public const uint GL_INTERNALFORMAT_STENCIL_TYPE = 33405;
        public const uint GL_MAX_WIDTH = 33406;
        public const uint GL_MAX_HEIGHT = 33407;
        public const uint GL_MAX_DEPTH = 33408;
        public const uint GL_MAX_LAYERS = 33409;
        public const uint GL_MAX_COMBINED_DIMENSIONS = 33410;
        public const uint GL_COLOR_COMPONENTS = 33411;
        public const uint GL_DEPTH_COMPONENTS = 33412;
        public const uint GL_STENCIL_COMPONENTS = 33413;
        public const uint GL_COLOR_RENDERABLE = 33414;
        public const uint GL_DEPTH_RENDERABLE = 33415;
        public const uint GL_STENCIL_RENDERABLE = 33416;
        public const uint GL_FRAMEBUFFER_RENDERABLE = 33417;
        public const uint GL_FRAMEBUFFER_RENDERABLE_LAYERED = 33418;
        public const uint GL_FRAMEBUFFER_BLEND = 33419;
        public const uint GL_READ_PIXELS = 33420;
        public const uint GL_READ_PIXELS_FORMAT = 33421;
        public const uint GL_READ_PIXELS_TYPE = 33422;
        public const uint GL_TEXTURE_IMAGE_FORMAT = 33423;
        public const uint GL_TEXTURE_IMAGE_TYPE = 33424;
        public const uint GL_GET_TEXTURE_IMAGE_FORMAT = 33425;
        public const uint GL_GET_TEXTURE_IMAGE_TYPE = 33426;
        public const uint GL_MIPMAP = 33427;
        public const uint GL_MANUAL_GENERATE_MIPMAP = 33428;
        public const uint GL_AUTO_GENERATE_MIPMAP = 33429;
        public const uint GL_COLOR_ENCODING = 33430;
        public const uint GL_SRGB_READ = 33431;
        public const uint GL_SRGB_WRITE = 33432;
        public const uint GL_FILTER = 33434;
        public const uint GL_VERTEX_TEXTURE = 33435;
        public const uint GL_TESS_CONTROL_TEXTURE = 33436;
        public const uint GL_TESS_EVALUATION_TEXTURE = 33437;
        public const uint GL_GEOMETRY_TEXTURE = 33438;
        public const uint GL_FRAGMENT_TEXTURE = 33439;
        public const uint GL_COMPUTE_TEXTURE = 33440;
        public const uint GL_TEXTURE_SHADOW = 33441;
        public const uint GL_TEXTURE_GATHER = 33442;
        public const uint GL_TEXTURE_GATHER_SHADOW = 33443;
        public const uint GL_SHADER_IMAGE_LOAD = 33444;
        public const uint GL_SHADER_IMAGE_STORE = 33445;
        public const uint GL_SHADER_IMAGE_ATOMIC = 33446;
        public const uint GL_IMAGE_TEXEL_SIZE = 33447;
        public const uint GL_IMAGE_COMPATIBILITY_CLASS = 33448;
        public const uint GL_IMAGE_PIXEL_FORMAT = 33449;
        public const uint GL_IMAGE_PIXEL_TYPE = 33450;
        public const uint GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST = 33452;
        public const uint GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST = 33453;
        public const uint GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE = 33454;
        public const uint GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE = 33455;
        public const uint GL_TEXTURE_COMPRESSED_BLOCK_WIDTH = 33457;
        public const uint GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT = 33458;
        public const uint GL_TEXTURE_COMPRESSED_BLOCK_SIZE = 33459;
        public const uint GL_CLEAR_BUFFER = 33460;
        public const uint GL_TEXTURE_VIEW = 33461;
        public const uint GL_VIEW_COMPATIBILITY_CLASS = 33462;
        public const uint GL_FULL_SUPPORT = 33463;
        public const uint GL_CAVEAT_SUPPORT = 33464;
        public const uint GL_IMAGE_CLASS_4_X_32 = 33465;
        public const uint GL_IMAGE_CLASS_2_X_32 = 33466;
        public const uint GL_IMAGE_CLASS_1_X_32 = 33467;
        public const uint GL_IMAGE_CLASS_4_X_16 = 33468;
        public const uint GL_IMAGE_CLASS_2_X_16 = 33469;
        public const uint GL_IMAGE_CLASS_1_X_16 = 33470;
        public const uint GL_IMAGE_CLASS_4_X_8 = 33471;
        public const uint GL_IMAGE_CLASS_2_X_8 = 33472;
        public const uint GL_IMAGE_CLASS_1_X_8 = 33473;
        public const uint GL_IMAGE_CLASS_11_11_10 = 33474;
        public const uint GL_IMAGE_CLASS_10_10_10_2 = 33475;
        public const uint GL_VIEW_CLASS_128_BITS = 33476;
        public const uint GL_VIEW_CLASS_96_BITS = 33477;
        public const uint GL_VIEW_CLASS_64_BITS = 33478;
        public const uint GL_VIEW_CLASS_48_BITS = 33479;
        public const uint GL_VIEW_CLASS_32_BITS = 33480;
        public const uint GL_VIEW_CLASS_24_BITS = 33481;
        public const uint GL_VIEW_CLASS_16_BITS = 33482;
        public const uint GL_VIEW_CLASS_8_BITS = 33483;
        public const uint GL_VIEW_CLASS_S3TC_DXT1_RGB = 33484;
        public const uint GL_VIEW_CLASS_S3TC_DXT1_RGBA = 33485;
        public const uint GL_VIEW_CLASS_S3TC_DXT3_RGBA = 33486;
        public const uint GL_VIEW_CLASS_S3TC_DXT5_RGBA = 33487;
        public const uint GL_VIEW_CLASS_RGTC1_RED = 33488;
        public const uint GL_VIEW_CLASS_RGTC2_RG = 33489;
        public const uint GL_VIEW_CLASS_BPTC_UNORM = 33490;
        public const uint GL_VIEW_CLASS_BPTC_FLOAT = 33491;
        public const uint GL_UNIFORM = 37601;
        public const uint GL_UNIFORM_BLOCK = 37602;
        public const uint GL_PROGRAM_INPUT = 37603;
        public const uint GL_PROGRAM_OUTPUT = 37604;
        public const uint GL_BUFFER_VARIABLE = 37605;
        public const uint GL_SHADER_STORAGE_BLOCK = 37606;
        public const uint GL_VERTEX_SUBROUTINE = 37608;
        public const uint GL_TESS_CONTROL_SUBROUTINE = 37609;
        public const uint GL_TESS_EVALUATION_SUBROUTINE = 37610;
        public const uint GL_GEOMETRY_SUBROUTINE = 37611;
        public const uint GL_FRAGMENT_SUBROUTINE = 37612;
        public const uint GL_COMPUTE_SUBROUTINE = 37613;
        public const uint GL_VERTEX_SUBROUTINE_UNIFORM = 37614;
        public const uint GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 37615;
        public const uint GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 37616;
        public const uint GL_GEOMETRY_SUBROUTINE_UNIFORM = 37617;
        public const uint GL_FRAGMENT_SUBROUTINE_UNIFORM = 37618;
        public const uint GL_COMPUTE_SUBROUTINE_UNIFORM = 37619;
        public const uint GL_TRANSFORM_FEEDBACK_VARYING = 37620;
        public const uint GL_ACTIVE_RESOURCES = 37621;
        public const uint GL_MAX_NAME_LENGTH = 37622;
        public const uint GL_MAX_NUM_ACTIVE_VARIABLES = 37623;
        public const uint GL_MAX_NUM_COMPATIBLE_SUBROUTINES = 37624;
        public const uint GL_NAME_LENGTH = 37625;
        public const uint GL_TYPE = 37626;
        public const uint GL_ARRAY_SIZE = 37627;
        public const uint GL_OFFSET = 37628;
        public const uint GL_BLOCK_INDEX = 37629;
        public const uint GL_ARRAY_STRIDE = 37630;
        public const uint GL_MATRIX_STRIDE = 37631;
        public const uint GL_IS_ROW_MAJOR = 37632;
        public const uint GL_ATOMIC_COUNTER_BUFFER_INDEX = 37633;
        public const uint GL_BUFFER_BINDING = 37634;
        public const uint GL_BUFFER_DATA_SIZE = 37635;
        public const uint GL_NUM_ACTIVE_VARIABLES = 37636;
        public const uint GL_ACTIVE_VARIABLES = 37637;
        public const uint GL_REFERENCED_BY_VERTEX_SHADER = 37638;
        public const uint GL_REFERENCED_BY_TESS_CONTROL_SHADER = 37639;
        public const uint GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 37640;
        public const uint GL_REFERENCED_BY_GEOMETRY_SHADER = 37641;
        public const uint GL_REFERENCED_BY_FRAGMENT_SHADER = 37642;
        public const uint GL_REFERENCED_BY_COMPUTE_SHADER = 37643;
        public const uint GL_TOP_LEVEL_ARRAY_SIZE = 37644;
        public const uint GL_TOP_LEVEL_ARRAY_STRIDE = 37645;
        public const uint GL_LOCATION = 37646;
        public const uint GL_LOCATION_INDEX = 37647;
        public const uint GL_IS_PER_PATCH = 37607;
        public const uint GL_SHADER_STORAGE_BUFFER = 37074;
        public const uint GL_SHADER_STORAGE_BUFFER_BINDING = 37075;
        public const uint GL_SHADER_STORAGE_BUFFER_START = 37076;
        public const uint GL_SHADER_STORAGE_BUFFER_SIZE = 37077;
        public const uint GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 37078;
        public const uint GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 37079;
        public const uint GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 37080;
        public const uint GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 37081;
        public const uint GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 37082;
        public const uint GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 37083;
        public const uint GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 37084;
        public const uint GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 37085;
        public const uint GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 37086;
        public const uint GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 37087;
        public const uint GL_SHADER_STORAGE_BARRIER_BIT = 8192;
        public const uint GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 36665;
        public const uint GL_DEPTH_STENCIL_TEXTURE_MODE = 37098;
        public const uint GL_TEXTURE_BUFFER_OFFSET = 37277;
        public const uint GL_TEXTURE_BUFFER_SIZE = 37278;
        public const uint GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 37279;
        public const uint GL_TEXTURE_VIEW_MIN_LEVEL = 33499;
        public const uint GL_TEXTURE_VIEW_NUM_LEVELS = 33500;
        public const uint GL_TEXTURE_VIEW_MIN_LAYER = 33501;
        public const uint GL_TEXTURE_VIEW_NUM_LAYERS = 33502;
        public const uint GL_TEXTURE_IMMUTABLE_LEVELS = 33503;
        public const uint GL_VERTEX_ATTRIB_BINDING = 33492;
        public const uint GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 33493;
        public const uint GL_VERTEX_BINDING_DIVISOR = 33494;
        public const uint GL_VERTEX_BINDING_OFFSET = 33495;
        public const uint GL_VERTEX_BINDING_STRIDE = 33496;
        public const uint GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 33497;
        public const uint GL_MAX_VERTEX_ATTRIB_BINDINGS = 33498;
        public const uint GL_VERTEX_BINDING_BUFFER = 36687;
        #endregion

        #region Delegates
        public delegate void GLDEBUGPROC(uint source, uint type, uint id, uint severity, int length, [In] [MarshalAs(UnmanagedType.LPStr)] string message, IntPtr userParam);
        public delegate void PFNGLCLEARBUFFERDATAPROC(uint target, uint internalformat, uint format, uint type, IntPtr data);
        public delegate void PFNGLCLEARBUFFERSUBDATAPROC(uint target, uint internalformat, int offset, int size, uint format, uint type, IntPtr data);
        public delegate void PFNGLDISPATCHCOMPUTEPROC(uint num_groups_x, uint num_groups_y, uint num_groups_z);
        public delegate void PFNGLDISPATCHCOMPUTEINDIRECTPROC(int indirect);
        public delegate void PFNGLCOPYIMAGESUBDATAPROC(uint srcName, uint srcTarget, int srcLevel, int srcX, int srcY, int srcZ, uint dstName, uint dstTarget, int dstLevel, int dstX, int dstY, int dstZ, int srcWidth, int srcHeight, int srcDepth);
        public delegate void PFNGLFRAMEBUFFERPARAMETERIPROC(uint target, uint pname, int param);
        public delegate void PFNGLGETFRAMEBUFFERPARAMETERIVPROC(uint target, uint pname, ref int parameters);
        public delegate void PFNGLGETINTERNALFORMATI64VPROC(uint target, uint internalformat, uint pname, int bufSize, ref int parameters);
        public delegate void PFNGLINVALIDATETEXSUBIMAGEPROC(uint texture, int level, int xoffset, int yoffset, int zoffset, int width, int height, int depth);
        public delegate void PFNGLINVALIDATETEXIMAGEPROC(uint texture, int level);
        public delegate void PFNGLINVALIDATEBUFFERSUBDATAPROC(uint buffer, int offset, int length);
        public delegate void PFNGLINVALIDATEBUFFERDATAPROC(uint buffer);
        public delegate void PFNGLINVALIDATEFRAMEBUFFERPROC(uint target, int numAttachments, ref uint attachments);
        public delegate void PFNGLINVALIDATESUBFRAMEBUFFERPROC(uint target, int numAttachments, ref uint attachments, int x, int y, int width, int height);
        public delegate void PFNGLMULTIDRAWARRAYSINDIRECTPROC(uint mode, IntPtr indirect, int drawcount, int stride);
        public delegate void PFNGLMULTIDRAWELEMENTSINDIRECTPROC(uint mode, uint type, IntPtr indirect, int drawcount, int stride);
        public delegate void PFNGLGETPROGRAMINTERFACEIVPROC(uint program, uint programInterface, uint pname, ref int parameters);
        public delegate uint PFNGLGETPROGRAMRESOURCEINDEXPROC(uint program, uint programInterface, [In] [MarshalAs(UnmanagedType.LPStr)] string name);
        public delegate void PFNGLGETPROGRAMRESOURCENAMEPROC(uint program, uint programInterface, uint index, int bufSize, ref int length, IntPtr name);
        public delegate void PFNGLGETPROGRAMRESOURCEIVPROC(uint program, uint programInterface, uint index, int propCount, ref uint props, int bufSize, ref int length, ref int parameters);
        public delegate int PFNGLGETPROGRAMRESOURCELOCATIONPROC(uint program, uint programInterface, [In] [MarshalAs(UnmanagedType.LPStr)] string name);
        public delegate int PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC(uint program, uint programInterface, [In] [MarshalAs(UnmanagedType.LPStr)] string name);
        public delegate void PFNGLSHADERSTORAGEBLOCKBINDINGPROC(uint program, uint storageBlockIndex, uint storageBlockBinding);
        public delegate void PFNGLTEXBUFFERRANGEPROC(uint target, uint internalformat, uint buffer, int offset, int size);
        public delegate void PFNGLTEXSTORAGE2DMULTISAMPLEPROC(uint target, int samples, uint internalformat, int width, int height, byte fixedsamplelocations);
        public delegate void PFNGLTEXSTORAGE3DMULTISAMPLEPROC(uint target, int samples, uint internalformat, int width, int height, int depth, byte fixedsamplelocations);
        public delegate void PFNGLTEXTUREVIEWPROC(uint texture, uint target, uint origtexture, uint internalformat, uint minlevel, uint numlevels, uint minlayer, uint numlayers);
        public delegate void PFNGLBINDVERTEXBUFFERPROC(uint bindingindex, uint buffer, int offset, int stride);
        public delegate void PFNGLVERTEXATTRIBFORMATPROC(uint attribindex, int size, uint type, byte normalized, uint relativeoffset);
        public delegate void PFNGLVERTEXATTRIBIFORMATPROC(uint attribindex, int size, uint type, uint relativeoffset);
        public delegate void PFNGLVERTEXATTRIBLFORMATPROC(uint attribindex, int size, uint type, uint relativeoffset);
        public delegate void PFNGLVERTEXATTRIBBINDINGPROC(uint attribindex, uint bindingindex);
        public delegate void PFNGLVERTEXBINDINGDIVISORPROC(uint bindingindex, uint divisor);
        public delegate void PFNGLDEBUGMESSAGECONTROLPROC(uint source, uint type, uint severity, int count, ref uint ids, byte enabled);
        public delegate void PFNGLDEBUGMESSAGEINSERTPROC(uint source, uint type, uint id, uint severity, int length, [In] [MarshalAs(UnmanagedType.LPStr)] string buf);
        public delegate void PFNGLDEBUGMESSAGECALLBACKPROC(GLDEBUGPROC callback, IntPtr userParam);
        public delegate uint PFNGLGETDEBUGMESSAGELOGPROC(uint count, int bufSize, ref uint sources, ref uint types, ref uint ids, ref uint severities, ref int lengths, IntPtr messageLog);
        public delegate void PFNGLPUSHDEBUGGROUPPROC(uint source, uint id, int length, [In] [MarshalAs(UnmanagedType.LPStr)] string message);
        public delegate void PFNGLPOPDEBUGGROUPPROC();
        public delegate void PFNGLOBJECTLABELPROC(uint identifier, uint name, int length, [In] [MarshalAs(UnmanagedType.LPStr)] string label);
        public delegate void PFNGLGETOBJECTLABELPROC(uint identifier, uint name, int bufSize, ref int length, IntPtr label);
        public delegate void PFNGLOBJECTPTRLABELPROC(IntPtr ptr, int length, [In] [MarshalAs(UnmanagedType.LPStr)] string label);
        public delegate void PFNGLGETOBJECTPTRLABELPROC(IntPtr ptr, int bufSize, ref int length, IntPtr label);
        #endregion

        #region Methods
#pragma warning disable 0649
        public static PFNGLCLEARBUFFERDATAPROC glClearBufferData;
        public static PFNGLCLEARBUFFERSUBDATAPROC glClearBufferSubData;
        public static PFNGLDISPATCHCOMPUTEPROC glDispatchCompute;
        public static PFNGLDISPATCHCOMPUTEINDIRECTPROC glDispatchComputeIndirect;
        public static PFNGLCOPYIMAGESUBDATAPROC glCopyImageSubData;
        public static PFNGLFRAMEBUFFERPARAMETERIPROC glFramebufferParameteri;
        public static PFNGLGETFRAMEBUFFERPARAMETERIVPROC glGetFramebufferParameteriv;
        public static PFNGLGETINTERNALFORMATI64VPROC glGetInternalformati64v;
        public static PFNGLINVALIDATETEXSUBIMAGEPROC glInvalidateTexSubImage;
        public static PFNGLINVALIDATETEXIMAGEPROC glInvalidateTexImage;
        public static PFNGLINVALIDATEBUFFERSUBDATAPROC glInvalidateBufferSubData;
        public static PFNGLINVALIDATEBUFFERDATAPROC glInvalidateBufferData;
        public static PFNGLINVALIDATEFRAMEBUFFERPROC glInvalidateFramebuffer;
        public static PFNGLINVALIDATESUBFRAMEBUFFERPROC glInvalidateSubFramebuffer;
        public static PFNGLMULTIDRAWARRAYSINDIRECTPROC glMultiDrawArraysIndirect;
        public static PFNGLMULTIDRAWELEMENTSINDIRECTPROC glMultiDrawElementsIndirect;
        public static PFNGLGETPROGRAMINTERFACEIVPROC glGetProgramInterfaceiv;
        public static PFNGLGETPROGRAMRESOURCEINDEXPROC glGetProgramResourceIndex;
        public static PFNGLGETPROGRAMRESOURCENAMEPROC glGetProgramResourceName;
        public static PFNGLGETPROGRAMRESOURCEIVPROC glGetProgramResourceiv;
        public static PFNGLGETPROGRAMRESOURCELOCATIONPROC glGetProgramResourceLocation;
        public static PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC glGetProgramResourceLocationIndex;
        public static PFNGLSHADERSTORAGEBLOCKBINDINGPROC glShaderStorageBlockBinding;
        public static PFNGLTEXBUFFERRANGEPROC glTexBufferRange;
        public static PFNGLTEXSTORAGE2DMULTISAMPLEPROC glTexStorage2DMultisample;
        public static PFNGLTEXSTORAGE3DMULTISAMPLEPROC glTexStorage3DMultisample;
        public static PFNGLTEXTUREVIEWPROC glTextureView;
        public static PFNGLBINDVERTEXBUFFERPROC glBindVertexBuffer;
        public static PFNGLVERTEXATTRIBFORMATPROC glVertexAttribFormat;
        public static PFNGLVERTEXATTRIBIFORMATPROC glVertexAttribIFormat;
        public static PFNGLVERTEXATTRIBLFORMATPROC glVertexAttribLFormat;
        public static PFNGLVERTEXATTRIBBINDINGPROC glVertexAttribBinding;
        public static PFNGLVERTEXBINDINGDIVISORPROC glVertexBindingDivisor;
        public static PFNGLDEBUGMESSAGECONTROLPROC glDebugMessageControl;
        public static PFNGLDEBUGMESSAGEINSERTPROC glDebugMessageInsert;
        public static PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback;
        public static PFNGLGETDEBUGMESSAGELOGPROC glGetDebugMessageLog;
        public static PFNGLPUSHDEBUGGROUPPROC glPushDebugGroup;
        public static PFNGLPOPDEBUGGROUPPROC glPopDebugGroup;
        public static PFNGLOBJECTLABELPROC glObjectLabel;
        public static PFNGLGETOBJECTLABELPROC glGetObjectLabel;
        public static PFNGLOBJECTPTRLABELPROC glObjectPtrLabel;
        public static PFNGLGETOBJECTPTRLABELPROC glGetObjectPtrLabel;
        #endregion
    }
}
